### ISSUE TITLE
convert tool error when convert caffe model

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/Anakin#129]
liuhao@umaster:~/OpenSource/Anakin/tools/external_converter_v2$ python converter.py 
Traceback (most recent call last):
  File "converter.py", line 16, in <module>
    from parser import *
  File "/home/liuhao/OpenSource/Anakin/tools/external_converter_v2/parser/__init__.py", line 8, in <module>
    from graph import *
  File "/home/liuhao/OpenSource/Anakin/tools/external_converter_v2/parser/graph.py", line 6, in <module>
    from proto import *
  File "/home/liuhao/OpenSource/Anakin/tools/external_converter_v2/parser/proto/__init__.py", line 5, in <module>
    from graph_pb2 import *
  File "/home/liuhao/OpenSource/Anakin/tools/external_converter_v2/parser/proto/graph_pb2.py", line 15, in <module>
    import node_pb2 as node__pb2
  File "/home/liuhao/OpenSource/Anakin/tools/external_converter_v2/parser/proto/node_pb2.py", line 15, in <module>
    import operator_pb2 as operator__pb2
  File "/home/liuhao/OpenSource/Anakin/tools/external_converter_v2/parser/proto/operator_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x0eoperator.proto\"e\n\x07OpProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0eis_commutative\x18\x02 \x01(\x08\x12\x0e\n\x06in_num\x18\x03 \x01(\x05\x12\x0f\n\x07out_num\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\tb\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

**Comment by HaoLiuHust** [comment]
and the config file is:  
OPTIONS:
    Framework: CAFFE
    SavePath: ./output
    ResultName: resnet50
    Config:
        LaunchBoard: ON
        Server:
            ip: 127.0.0.1
            port: 8888
        OptimizedGraph: 
            enable: OFF
            path: ./output/resnet50.anakin.bin
    LOGGER:
        LogToPath: ./log/
        WithColor: ON 

TARGET:
    CAFFE:
        # path to proto files   
        ProtoPaths:
            - /home/liuhao/framework/caffe/src/caffe/proto/caffe.proto
        PrototxtPath: ./ResNet-50-deploy.prototxt
        ModelPath: ./ResNet-50-model.caffemodel

**Comment by HaoLiuHust** [comment]
seems protobuf need to be 3.4.0. After us protobuf 3.4, the error disappeared, but there will be another problem about caffe_yolo_pb, make some change to script will ignore this.

**Comment by qichaotang** [comment]
@HaoLiuHust hi, you convert tool successs?
