### ISSUE TITLE
使用external_converter_v2目录下的converter.py转换caffemodle模型失败

### ISSUE THREAD

**Issue by kezunlin** [PaddlePaddle/Anakin#462]
```
python converter.py
INF | 2018-09-20 14:02:34.567382 | __init__.py:20 <module>() ]  Import Module: caffe_pb2
INF | 2018-09-20 14:02:34.581084 | parser_caffe.py:470 _Parsing_new() ]   [CAFFE] Parsing ...
Traceback (most recent call last):
  File "converter.py", line 20, in <module>
    graph = Graph(config)
  File "/home/kezunlin/program/anakin/tools/external_converter_v2/parser/graph.py", line 39, in __init__
    self.graph_io = self.parser()
  File "/home/kezunlin/program/anakin/tools/external_converter_v2/parser/caffe/parser_caffe.py", line 34, in __call__
    return self._Parsing_new()
  File "/home/kezunlin/program/anakin/tools/external_converter_v2/parser/caffe/parser_caffe.py", line 471, in _Parsing_new
    self._DetectionArch()
  File "/home/kezunlin/program/anakin/tools/external_converter_v2/parser/caffe/parser_caffe.py", line 41, in _DetectionArch
    self._FilterNet()
  File "/home/kezunlin/program/anakin/tools/external_converter_v2/parser/caffe/parser_caffe.py", line 389, in _FilterNet
    assert layer.name not in filtered_layer_names, " layer_name : %s" % (layer.name)
AssertionError:  layer_name : fusion5
```

**Comment by Shixiaowei02** [comment]
您好，这是由于我们的 layer 目前还不支持 fusion5 导致的问题。请您将这一层的功能和你们的需求发邮件至 anakin@baidu.com，或者通过百度 hi 联系。谢谢！
